config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root to: "problems#index"

  resources :users, only: [:edit, :update, :show]
  resources :problems, only: [:index, :new, :create, :show, :destroy] do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end

end

app/models/age.rb
class Age < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '10歳以下' },
    { id: 2, name: '10代' },
    { id: 3, name: '20代' },
    { id: 4, name: '30代' },
    { id: 5, name: '40代' },
    { id: 6, name: '50代' },
    { id: 7, name: '60歳以上' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '恋愛・結婚' },
    { id: 2, name: 'お金・法律' },
    { id: 3, name: '人間関係' },
    { id: 4, name: '仕事・キャリア' },
    { id: 5, name: '健康・メンタルヘルス' },
    { id: 6, name: '家庭・家族' },
    { id: 7, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :problems

  def self.ransackable_attributes(auth_object = nil)
    %w[id name]
  end
  
  def self.ransackable_associations(auth_object = nil)
    %w[]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :problem
  belongs_to :user
  has_one_attached :image

  validates :solution, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '小学生' },
    { id: 2, name: '中学生' },
    { id: 3, name: '高校生' },
    { id: 4, name: '大学生' },
    { id: 5, name: '会社員' },
    { id: 6, name: '公務員' },
    { id: 7, name: '自由業' },
    { id: 8, name: '専業主婦' },
    { id: 9, name: 'パート・アルバイト' },
    { id: 10, name: '無職' },
    { id: 11, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  validates :title,   presence: true
  validates :content, presence: true
  validates :category_id, numericality: { other_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,        presence: true
  validates :password,    format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,100}+\z/i }, on: :create
  validates :gender,      presence: true
  validates :age_id,      numericality: { other_than: 0 }
  validates :position_id, numericality: { other_than: 0 }

  has_many :problems
  has_many :comments
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :age
  belongs_to :position
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :age_id, :position_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/problems/#{comment.problem.id}"
  end

  private

  def comment_params
    params.require(:comment).permit(:solution, :image).merge(user_id: current_user.id, problem_id: params[:problem_id])
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :search_category, only: [:index, :search]

  def index
    @problems = Problem.all.order(created_at: :desc)
    search_category
    @results = @p.result.order(created_at: :desc)
  end

  def new
    @problem = Problem.new
  end

  def create
    @problem = Problem.new(problem_params)
    if @problem.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @problem = Problem.find(params[:id])
    @comment = Comment.new
    @comments = @problem.comments.includes(:user)
  end

  def destroy
    problem = Problem.find(params[:id])
    problem.destroy
    redirect_to root_path
  end

  def search
    @results = @p.result.order(created_at: :desc)
  end

  private

  def problem_params
    params.require(:problem).permit(:title, :content, :category_id).merge(user_id: current_user.id)
  end

  def search_category
    @p = Problem.ransack(params[:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :gender, :age_id, :position_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SolveApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/problems/_comment.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= link_to comment.user.name, user_path(comment.user) %>
    </div>
    <div class="message-date">
      <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= comment.solution %>
    </div>
    <%= image_tag comment.image.variant(resize: '500x500'), class: 'message-image' if comment.image.attached? %>
  </div>
</div>

app/views/problems/_main_chat.html.erb
<div class="chat-room-header">
  <div class="left-header">
    <div class="title">
      <%= link_to "〜お悩み相談室〜", root_path %> 
    </div>
  </div>
  <div class="left-header">
    <div class="header-title">
      タイトル：　
      <div class="title-name"><%= @problem.title %>　　　</div>
      <%= link_to @problem.user.name, user_path(@problem.user) %>　さんのお悩み
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <% if user_signed_in? && current_user.id == @problem.user_id %>
        <%= link_to "お悩み解決‼️", problem_path(@problem), method: :delete %>
      <%end%>
    </div>
  </div>
</div>

<div class="problem-content">
  <p>カテゴリー：　<%= @problem.category.name %></p>
  <p>相談内容：　<%= @problem.content %></p>
</div>

<div class="messages">
  <%= render partial: 'comment', collection: @comments %>
</div>

<% if user_signed_in? %>
  <%= form_with model: [@problem, @comment], class: 'form', local: true do |f| %>
    <div class="form-input">
      <%= f.text_field :solution, class: 'form-message', placeholder: 'コメントする' %>
      <label class="form-image">
        <span class="image-file">画像</span>
        <%= f.file_field :image, class: 'hidden' %>
      </label>
    </div>
    <%= f.submit '送信', class: 'form-submit' %>
  <% end %>
<%else%>
  <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
<%end%>

app/views/problems/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to "相談する", new_problem_path %>
  </div>
</div>

<div class="rooms">
  <div class="my-problem">＜Myお悩み一覧＞</div>
  <% current_user.problems.each do |problem| %>
    <div class="room">
      <div class="room-name">
        ⚫︎　<%= link_to problem.title, problem_path(problem.id) %>
      </div>
    </div>
  <% end %>
</div>

app/views/problems/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <div class="chat-header">
      <div class="left-header">
        <div class="title">
          <%= link_to "〜お悩み相談室〜", root_path %> 
        </div>
      </div>
    </div>
    <div class="title-contents">
      <div class="service-title">Solve a problem</div>
      <div class="service-content">悩みがあることは、生きている証。</div>
      <div class="service-content">あなたが抱えている悩みを解決します。</div>
    </div>
    <div class="top-messages">
      <div class="top-page">＜お悩み一覧＞</div>
      <%= search_form_for @p, class: 'search-form', url: search_problems_path do |f| %>
        <%= f.label :category_name_eq, '・カテゴリー検索：', class:'search-title' %>
        <%= f.collection_select(:category_id_eq,Category.all,:id,:name,{},{class:'search-category'}) %>
        <%= f.submit '検索', class:'search-form-submit'%>
      <% end %>
      <% @problems.each do |problem| %>
        <div class="room">
          <div class="rooms-name">
            ⚫︎　<%= link_to problem.title, problem_path(problem.id) %>　　
            <%= link_to problem.user.name, user_path(problem.user) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/problems/new.html.erb
<div class='chat-room-form'>
  <h1>お悩み相談</h1>
  <%=form_with model: @problem, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :タイトル, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :title, class: 'chat__room_name chat-room-form__input', placeholder: '相談タイトルを入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    <div class='chat-room-form__field--left'>
        <%= f.label :カテゴリー, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"genre-select"}) %>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' >相談内容</label>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_area :content, class: 'chat__room_name chat-room-form__input_down', placeholder: '相談内容を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit '相談する', class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/problems/search.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <div class="chat-header">
      <div class="left-header">
        <div class="title">
          <%= link_to "〜お悩み相談室〜", root_path %> 
        </div>
      </div>
    </div>
    <div class="top-messages">
      <div class="top-page">＜お悩み一覧＞</div>
      <%= search_form_for @p, class: 'search-form', url: search_problems_path do |f| %>
        <%= f.label :category_name_eq, '・カテゴリー検索：', class:'search-title' %>
        <%= f.collection_select(:category_id_eq,Category.all,:id,:name,{},{class:'search-category'}) %>
        <%= f.submit '検索', class:'search-form-submit'%>
      <% end %>
      <% if @results.length !=0 %>
        <% @results.each do |result| %>
          <div class="room">
            <div class="rooms-name">
              ⚫︎　<%= link_to result.title, problem_path(result.id) %>　　
              <%= link_to result.user.name, user_path(result.user) %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="no-category">※該当するお悩みはありません</div>
      <% end %>
    </div>
  </div>
</div>

app/views/problems/show.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "トップページに戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
            <i>名前</i>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true %>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :gender %>
            <i>性別</i>
          </div>
          <%= f.radio_button :gender, '男性' %>
          <%= f.label :gender, '男性', value: "男性" %>
          <%= f.radio_button :gender, '女性' %>
          <%= f.label :gender, '女性', value: '女性' %>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :age %>
            <i>年代</i>
          </div>
          <%= f.collection_select(:age_id, Age.all, :id, :name, {}, {class:"genre-select"}) %>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :position %>
            <i>肩書き</i>
          </div>
          <%= f.collection_select(:position_id, Position.all, :id, :name, {}, {class:"genre-select"}) %>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Show Account</h2>
      <h5>ユーザー詳細</h5>
      <%= link_to "トップページに戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
        <div class='field'>
          <div class='field-label'>
            <h3>Name <i>名前</i>：　　　<%= @user.name %></h3>
          </div>
          <div class='field-input'>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <h3>Gender <i>性別</i>：　　<%= @user.gender %></h3>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <h3>Age <i>年代</i>：　　　　<%= @user.age.name %></h3>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <h3>Position <i>肩書き</i>：　<%= @user.position.name %></h3>
          </div>
        </div>
        <div class='actions'>
        </div>
    </div>
  </div>
</div>